Repository UserOfficeProject/user-office-lib, pull requests merged in 2022-03, with the labels that each got.

#105 Fix: Increase max comment length to 1000 characters
  packages/logger/package-lock.json
  packages/message-broker/package-lock.json
  packages/uows-client-generator/package-lock.json
  packages/validation/package-lock.json
  packages/validation/package.json
  packages/validation/src/Call/index.ts
  packages/validation/src/Instrument/index.ts
  packages/validation/src/Review/index.ts
  packages/validation/src/SEP/index.ts
  packages/validation/src/Template/index.ts
  packages/validation/src/User/index.ts
Labels: Fix

#108 fix: Max must be greater than min
  packages/validation/src/Questionary/interval.ts
Labels: bug

#109 refactor: replace moment with luxon and improve date validation error message
  packages/uows-client-generator/package-lock.json
  packages/validation/package-lock.json
  packages/validation/package.json
  packages/validation/src/Equipment/index.ts
  packages/validation/src/LostTime/index.ts
  packages/validation/src/Questionary/date.ts
  packages/validation/src/ScheduledEvent/index.ts
Labels: type: feature, type: refactor, review: please, refactor

#110 feat: update and improve call create/update validation
  packages/validation/package-lock.json
  packages/validation/package.json
  packages/validation/src/Call/index.ts
  packages/validation/src/util.ts
Labels: enhancement
