Repository UserOfficeProject/user-office-lib, pull requests merged in 2022-04, with the labels that each got.

#113 fix(review): make grade comment required #SWAP-2478
  package.json
  packages/localisation/package.json
  packages/logger/package.json
  packages/message-broker/package.json
  packages/uows-client-generator/package-lock.json
  packages/uows-client-generator/package.json
  packages/validation/package-lock.json
  packages/validation/package.json
  packages/validation/src/Review/index.ts
Labels: bug

#119 chore: set matching npm version for node
  package-lock.json
  package.json
Labels: chore

#120 fix(reviews): remove limit from YUP
  packages/validation/package-lock.json
  packages/validation/package.json
  packages/validation/src/Review/index.ts
Labels: bug

#121 feat: make status and timeAllocation required on technical review update or submit
  packages/validation/package-lock.json
  packages/validation/package.json
  packages/validation/src/Review/index.ts
Labels: enhancement

#124 fix(password confirmation): use better validation schema for password confirmation when creating user or reseting passwords
  package-lock.json
  package.json
  packages/uows-client-generator/package-lock.json
  packages/validation/package-lock.json
  packages/validation/package.json
  packages/validation/src/User/index.ts
Labels: bug, review: please
